apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  labels:
    name: kubia
spec:
  containers:
  - name: kubia
    image: tomcat
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
