apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-10-05T13:13:08Z"
  generateName: kubia-
  labels:
    run: kubia
  name: kubia-zj68p
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: kubia
    uid: 7939300e-dd15-4740-801b-2ac0a6a6fe10
  resourceVersion: "16013"
  selfLink: /api/v1/namespaces/default/pods/kubia-zj68p
  uid: 8ec49578-0653-4952-bcc0-9a24411811db
spec:
  containers:
  - image: tomcat:8.0
    imagePullPolicy: IfNotPresent
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-qnt9v
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-qnt9v
    secret:
      defaultMode: 420
      secretName: default-token-qnt9v
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-10-05T13:13:08Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-10-07T11:24:43Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-10-07T11:24:43Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-10-05T13:13:08Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b2ac182102872952e16e6727ca033ff3b8d38c361e3f912a383b8cbd33101d5f
    image: tomcat:8.0
    imageID: docker-pullable://tomcat@sha256:8ecb10948deb32c34aeadf7bf95d12a93fbd3527911fa629c1a3e7823b89ce6f
    lastState:
      terminated:
        containerID: docker://34027d5f82b835bf1b23198c04c480279a8f7d91d85ec04ae621ee0d2c780e40
        exitCode: 255
        finishedAt: "2019-10-07T11:23:54Z"
        reason: Error
        startedAt: "2019-10-05T13:13:09Z"
    name: kubia
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: "2019-10-07T11:24:43Z"
  hostIP: 192.168.122.248
  phase: Running
  podIP: 172.17.0.2
  qosClass: BestEffort
  startTime: "2019-10-05T13:13:08Z"
